services:
    app:
        build:
            context: .
            dockerfile: Dockerfile
        container_name: crm-app
        restart: unless-stopped
        tty: true
        environment:
            SERVICE_TAGS: dev
            SERVICE_NAME: app
        working_dir: /var/www/html
        volumes:
            - ./:/var/www/html
            - ./docker/php/local.ini:/usr/local/etc/php/conf.d/local.ini
        depends_on:
            - db
        networks:
            - app-network

    webserver:
        image: nginx:alpine
        container_name: crm-webserver
        restart: unless-stopped
        tty: true
        ports:
            - 8000:80
        volumes:
            - ./:/var/www/html
            - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
        depends_on:
            - app
            - db
        networks:
            - app-network

    db:
        image: mysql:8
        container_name: crm-db
        restart: unless-stopped
        tty: true
        ports:
            - 3306:3306
        environment:
            SERVICE_TAGS: dev
            SERVICE_NAME: database
            MYSQL_DATABASE: ${DB_DATABASE}
            MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
        volumes:
            - db_data:/var/lib/mysql/
            - ./docker/mysql/my.cnf:/etc/mysql/my.cnf
        networks:
            - app-network

    phpmyadmin:
        image: phpmyadmin:latest
        container_name: crm-phpmyadmin
        restart: unless-stopped
        tty: true
        ports:
            - 8001:80
        environment:
            PMA_HOST: db
        depends_on:
            - db
        networks:
            - app-network

networks:
    app-network:
        driver: bridge

volumes:
    db_data:
